<a href="https://colab.research.google.com/github/TonmoyTalukder/deep-learning-explore/blob/main/PyTorch_Explore/0_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Basics

In [ ]:
# !pip install torch

In [ ]:
import torch
x = torch.empty(2, 2, 2, 3)
print(x)

tensor([[[[1.6323e+23, 3.0945e-41, 1.6381e+23],
          [3.0945e-41, 1.5695e-43, 0.0000e+00]],

         [[1.5695e-43, 0.0000e+00, 1.4101e-37],
          [3.0949e-41, 0.0000e+00, 0.0000e+00]]],


        [[[1.4013e-45, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.4013e-45, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [ ]:
x = torch.rand(2, 2)
print(x)

tensor([[0.9898, 0.8585],
        [0.9009, 0.6108]])


In [ ]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
x = torch.zeros(2, 2, dtype=torch.double)
print(x.dtype)

torch.float64


In [ ]:
x = torch.zeros(2, 2, dtype=torch.double)
print(x.size())

torch.Size([2, 2])


In [ ]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x, y)
print(z)

tensor([[0.8600, 0.6114],
        [0.0664, 0.0166]])
tensor([[0.6956, 0.8311],
        [0.8279, 0.6232]])
tensor([[1.5556, 1.4425],
        [0.8944, 0.6399]])


In [ ]:
y.add_(x)
print(y)

tensor([[1.5556, 1.4425],
        [0.8944, 0.6399]])


In [ ]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.6956, -0.8311],
        [-0.8279, -0.6232]])


In [ ]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[1.3379, 0.8819],
        [0.0594, 0.0106]])


In [ ]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.5529, 0.4238],
        [0.0743, 0.0260]])


In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

tensor([[0.0158, 0.4273, 0.3592],
        [0.2672, 0.4141, 0.8649],
        [0.2381, 0.2695, 0.3646],
        [0.2931, 0.1946, 0.2131],
        [0.1282, 0.6956, 0.8677]])


In [ ]:
print(x[:,0])

tensor([0.0158, 0.2672, 0.2381, 0.2931, 0.1282])


In [ ]:
print(x[1, :])

tensor([0.2672, 0.4141, 0.8649])


In [ ]:
print(x[1, 1])

tensor(0.4141)


In [ ]:
print(x[1, 1].item())

0.4140881299972534


In [ ]:
# Reshaping a Tensor
x = torch.rand(4,4)
print(x)

tensor([[0.5179, 0.7367, 0.6369, 0.3123],
        [0.3828, 0.2964, 0.1966, 0.7619],
        [0.4399, 0.7337, 0.7628, 0.4106],
        [0.0963, 0.5455, 0.6996, 0.2913]])


In [ ]:
y = x.view(16)
print(y)

tensor([0.5179, 0.7367, 0.6369, 0.3123, 0.3828, 0.2964, 0.1966, 0.7619, 0.4399,
        0.7337, 0.7628, 0.4106, 0.0963, 0.5455, 0.6996, 0.2913])


In [ ]:
y = x.view(-1, 8)
print(y.size())
print(y)

torch.Size([2, 8])
tensor([[0.5179, 0.7367, 0.6369, 0.3123, 0.3828, 0.2964, 0.1966, 0.7619],
        [0.4399, 0.7337, 0.7628, 0.4106, 0.0963, 0.5455, 0.6996, 0.2913]])


In [ ]:
# Convert Numpy to Tensor or Vice Versa
import numpy as np

a = torch.ones(5)
print(a, '\n')

b = a.numpy()
print(type(b))
print(b)

tensor([1., 1., 1., 1., 1.]) 

<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [ ]:
print(b)

[2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(5)
print(a, '\n')

b = torch.from_numpy(a) # dtype
print(b)

[1. 1. 1. 1. 1.] 

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a += 1
print(a)

[2. 2. 2. 2. 2.]


In [ ]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# For GPU

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    # z.numpy() will be error, cause numpy can handle only CPU tensor
    z = z.to("cpu")

    print(z)

## Gradient Calculation

In [ ]:
# Gradient for optimization

x = torch.ones(5, requires_grad=True) # By default it is false
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [ ]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1512,  0.1337, -0.5013], requires_grad=True)


In [ ]:
y = x + 2
print(y)

tensor([2.1512, 2.1337, 1.4987], grad_fn=<AddBackward0>)


In [ ]:
y = x - 2
print(y)

tensor([-1.8488, -1.8663, -2.5013], grad_fn=<SubBackward0>)


In [ ]:
y = x * x * 2
print(y)

tensor([0.0457, 0.0357, 0.5025], grad_fn=<MulBackward0>)


In [ ]:
y = x + 2
z = y * y * 2
z = z.mean() # Grad can only works in scaler vector
print(x)
print(y)
print(z)

tensor([ 0.1512,  0.1337, -0.5013], requires_grad=True)
tensor([2.1512, 2.1337, 1.4987], grad_fn=<AddBackward0>)
tensor(7.6175, grad_fn=<MeanBackward0>)


In [ ]:
z.backward() # dy/dx
print(x.grad)

tensor([5.9380, 5.8680, 3.3283])


In [ ]:
z = y * y * 2
print(z)
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32) # if z is not scaler we should give a vector
z.backward(v) # dy/dx
print(x.grad)

tensor([9.2550, 9.1052, 4.4924], grad_fn=<MulBackward0>)
tensor([ 6.7985, 14.4028,  3.3343])


In [ ]:
# Prevent PyTorch to track history

import torch

x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x.requires_grad_(False)
print(x)

tensor([ 0.0531, -0.4992, -1.0324], requires_grad=True)
tensor([ 0.0531, -0.4992, -1.0324])


In [ ]:
x.detach()
print(x)

tensor([ 0.0531, -0.4992, -1.0324])


In [ ]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.0531, 1.5008, 0.9676])


In [ ]:
# Dummy Training

import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
import torch

weights = torch.ones(4, requires_grad=True)

# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()

# z.backward()
# weights.grad.zero_()

## Backpropagation

In [ ]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [ ]:
# backward pass
loss.backward()
print(w.grad)

tensor(-2.)


In [ ]:
# Update weights
# next forwad and backwards

## Gradients Numpy

In [ ]:
import numpy as np

# f = w * x
# f = 2 * x

X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32) # Multiply each value with 2

w = 0.0

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()

# gradient
# MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N 2x (w*x-y)
def gradient(x,y,y_predicted):
    return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 17

for epoch in range(n_iters):
    # prediction = forward_pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 1 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 2: w = 1.680, loss = 4.79999924
epoch 3: w = 1.872, loss = 0.76800019
epoch 4: w = 1.949, loss = 0.12288000
epoch 5: w = 1.980, loss = 0.01966083
epoch 6: w = 1.992, loss = 0.00314574
epoch 7: w = 1.997, loss = 0.00050331
epoch 8: w = 1.999, loss = 0.00008053
epoch 9: w = 1.999, loss = 0.00001288
epoch 10: w = 2.000, loss = 0.00000206
epoch 11: w = 2.000, loss = 0.00000033
epoch 12: w = 2.000, loss = 0.00000005
epoch 13: w = 2.000, loss = 0.00000001
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


## Gradients Torch

### gradientdescent manually

In [ ]:
import torch

# f = w * x
# f = 2 * x

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32) # Multiply each value with 2

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward_pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # gradients = backward pass
    l.backward() # dl/dw

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad

    # zero gradients
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


### gradientdescent auto

In [ ]:
# 1) Design Model (input, output size, forward pass)
# 2) Construct Loss and optimizer
# 3) Training Loop
#  - forward pass: compute prediction
#  - backward pass: gradients
#  - Update weights
#  - Iterated copuple of times

import torch
import torch.nn as nn # Neural Network modules
# f = w * x
# f = 2 * x

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32) # Multiply each value with 2

X_test = torch.tensor([5], dtype=torch.float32)

n_samples, n_features = X.shape
print(n_samples, n_features)

input_size = n_features
output_size = n_features

# model = nn.Linear(input_size, output_size)

class LinearRegression(nn.Module):

    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()

        # define layers
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)

model = LinearRegression(input_size, output_size)

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# Training
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
    # prediction = forward_pass
    y_pred = model(X)

    # loss
    l = loss(Y, y_pred)

    # gradients = backward pass
    l.backward() # dl/dw

    # update weights
    optimizer.step()

    # zero gradients
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters()
        print(f'epoch {epoch+1}: w = {w[0][0].item():.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

4 1
Prediction before training: f(5) = 1.119
epoch 1: w = 0.680, loss = 26.94902992
epoch 11: w = 1.866, loss = 0.70963287
epoch 21: w = 2.054, loss = 0.03003530
epoch 31: w = 2.082, loss = 0.01177294
epoch 41: w = 2.085, loss = 0.01066044
epoch 51: w = 2.083, loss = 0.01002889
epoch 61: w = 2.081, loss = 0.00944488
epoch 71: w = 2.078, loss = 0.00889511
epoch 81: w = 2.076, loss = 0.00837738
epoch 91: w = 2.074, loss = 0.00788977
Prediction after training: f(5) = 10.148
