<a href="https://colab.research.google.com/github/TonmoyTalukder/deep-learning-explore/blob/main/PyTorch_Explore/2_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset and DataLoader - Batch Training



```
epoch = 1 forward and backward pass of All training samples

batch_size = number of training samples in one forward & backward pass

number of iterations = number of passes, each pass using [batch_size] number of samples

e.g. 100 samples, batch_size=20 --> 100/20 = 5 iterations for 1 epoch

```



In [33]:
# data = numpy.loadtxt('wine.csv')

# training loop
# for epoch in range(1000):
#     x, y = data
# forward + backward + weight updates

In [34]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

class WineDataset(Dataset):

    def __init__(self):
        # data loading
        xy = np.loadtxt('./data/wine.csv',
                        delimiter=",",
                        dtype=np.float32,
                        skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]]) # n_samples, 1
        self.n_samples = xy.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.n_samples

dataset = WineDataset()

first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [35]:
# Load whole dataset with DataLoader
# shuffle: shuffle data, good for training
# num_workers: faster loading with multiple subprocesses

dataloader = DataLoader(dataset=dataset,
                        batch_size=4,
                        shuffle=True,
                        num_workers=2)

# convert to an iterator and look at one random sample
dataiter = iter(dataloader)
data = next(dataiter)
features, labels = data
print(features, labels)

tensor([[1.2600e+01, 1.3400e+00, 1.9000e+00, 1.8500e+01, 8.8000e+01, 1.4500e+00,
         1.3600e+00, 2.9000e-01, 1.3500e+00, 2.4500e+00, 1.0400e+00, 2.7700e+00,
         5.6200e+02],
        [1.2470e+01, 1.5200e+00, 2.2000e+00, 1.9000e+01, 1.6200e+02, 2.5000e+00,
         2.2700e+00, 3.2000e-01, 3.2800e+00, 2.6000e+00, 1.1600e+00, 2.6300e+00,
         9.3700e+02],
        [1.3770e+01, 1.9000e+00, 2.6800e+00, 1.7100e+01, 1.1500e+02, 3.0000e+00,
         2.7900e+00, 3.9000e-01, 1.6800e+00, 6.3000e+00, 1.1300e+00, 2.9300e+00,
         1.3750e+03],
        [1.3400e+01, 3.9100e+00, 2.4800e+00, 2.3000e+01, 1.0200e+02, 1.8000e+00,
         7.5000e-01, 4.3000e-01, 1.4100e+00, 7.3000e+00, 7.0000e-01, 1.5600e+00,
         7.5000e+02]]) tensor([[2.],
        [2.],
        [1.],
        [3.]])


In [36]:
# training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
# print(total_samples, n_iterations)

for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        # forward

        # backward

        # update

        if (i+1)%5 ==0:
            print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iterations}, inputs{inputs.shape}')

epoch 1/2, step 5/45, inputstorch.Size([4, 13])
epoch 1/2, step 10/45, inputstorch.Size([4, 13])
epoch 1/2, step 15/45, inputstorch.Size([4, 13])
epoch 1/2, step 20/45, inputstorch.Size([4, 13])
epoch 1/2, step 25/45, inputstorch.Size([4, 13])
epoch 1/2, step 30/45, inputstorch.Size([4, 13])
epoch 1/2, step 35/45, inputstorch.Size([4, 13])
epoch 1/2, step 40/45, inputstorch.Size([4, 13])
epoch 1/2, step 45/45, inputstorch.Size([2, 13])
epoch 2/2, step 5/45, inputstorch.Size([4, 13])
epoch 2/2, step 10/45, inputstorch.Size([4, 13])
epoch 2/2, step 15/45, inputstorch.Size([4, 13])
epoch 2/2, step 20/45, inputstorch.Size([4, 13])
epoch 2/2, step 25/45, inputstorch.Size([4, 13])
epoch 2/2, step 30/45, inputstorch.Size([4, 13])
epoch 2/2, step 35/45, inputstorch.Size([4, 13])
epoch 2/2, step 40/45, inputstorch.Size([4, 13])
epoch 2/2, step 45/45, inputstorch.Size([2, 13])


## Dataset Transforms


[https://pytorch.org/docs/stable/torchvision/transforms.html](https://pytorch.org/docs/stable/torchvision/transforms.html)
```

Transforms can be applied to PIL images, tensors, ndarrays, or custom data
during creation of the DataSet

complete list of built-in transforms:
https://pytorch.org/docs/stable/torchvision/transforms.html

On Images
---------
CenterCrop, Grayscale, Pad, RandomAffine
RandomCrop, RandomHorizontalFlip, RandomRotation
Resize, Scale

On Tensors
----------
LinearTransformation, Normalize, RandomErasing

Conversion
----------
ToPILImage: from tensor or ndrarray
ToTensor : from numpy.ndarray or PILImage

Generic
-------
Use Lambda

Custom
------
Write own class

Compose multiple Transforms
---------------------------
composed = transforms.Compose([Rescale(256),
                               RandomCrop(224)])

```



In [37]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

class WineDataset(Dataset):

    def __init__(self, transform=None):
        # data loading
        xy = np.loadtxt('./data/wine.csv',
                        delimiter=",",
                        dtype=np.float32,
                        skiprows=1)

        # Note: we do not convert to tensor here
        self.x = xy[:, 1:]
        self.y = xy[:, [0]] # n_samples, 1

        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]

        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        return self.n_samples

class ToTensor:

    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

class MulTransform:

    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

In [38]:
# Without Transform
dataset = WineDataset(transform = None)

first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [39]:
# With Tensor Transform
dataset = WineDataset(transform = ToTensor())

first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [40]:
# With Multiplication Transform
dataset = WineDataset(transform=MulTransform(4))

first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

[5.692e+01 6.840e+00 9.720e+00 6.240e+01 5.080e+02 1.120e+01 1.224e+01
 1.120e+00 9.160e+00 2.256e+01 4.160e+00 1.568e+01 4.260e+03]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [41]:
# With Tensor and Multiplication Transform
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(4)])
dataset = WineDataset(transform=composed)

first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
        1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
        4.2600e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>
