<a href="https://colab.research.google.com/github/TonmoyTalukder/deep-learning-explore/blob/main/PyTorch_Explore/8_Save_and_Load_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# Methods

import torch
import torch.nn as nn

torch.save(arg, PATH)
torch.load(PATH)
model.load_sate_dict(arg)



# Save

import torch
import torch.nn as nn

####  COMPLETE MODEL  ####
torch.save(arg, PATH)
model = torch.load(PATH)
model.eval()

####  STATE DICT  ####
torch.save(model.state_dict(), PATH) # it only saves parameters
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()
```



In [20]:
#  Save Load Example

import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear())
        return y_pred

model = Model(n_input_features=6)

print(model.state_dict())
# train model ...

OrderedDict([('linear.weight', tensor([[ 0.0033,  0.0729,  0.1773,  0.3808, -0.3613,  0.0527]])), ('linear.bias', tensor([0.2571]))])


In [21]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0033,  0.0729,  0.1773,  0.3808, -0.3613,  0.0527]],
       requires_grad=True)
Parameter containing:
tensor([0.2571], requires_grad=True)


In [22]:
####  LAZY OPTION  ####
FILE = "lazy_model.pth"
torch.save(model, FILE) # Save

modeltest = torch.load(FILE) # Load
modeltest.eval()

for param in modeltest.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0033,  0.0729,  0.1773,  0.3808, -0.3613,  0.0527]],
       requires_grad=True)
Parameter containing:
tensor([0.2571], requires_grad=True)


In [23]:
####  PREFARABLE WAY  ####
FILE = "pref_model.pth"
torch.save(model.state_dict(), FILE) # Save

loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE)) # Load
modeltest.eval()

for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0033,  0.0729,  0.1773,  0.3808, -0.3613,  0.0527]],
       requires_grad=True)
Parameter containing:
tensor([0.2571], requires_grad=True)


In [25]:
# Saving Checkpoints

import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear())
        return y_pred

model = Model(n_input_features=6)
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

print(optimizer.state_dict())
# train model ...

checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}

torch.save(checkpoint, "checkpoint.pth")

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [26]:
loaded_checkpoint = torch.load("checkpoint.pth")
epoch = loaded_checkpoint["epoch"]

model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["optim_state"])

print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}




```
# GPU | CPU Saving and Loading

import torch
import torch.nn as nn

# Save on GPU, Load on CPU
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), PATH)

device = torch.device("cpu")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))

# Save on GPU, Load on GPU
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), PATH)

model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.to(device)

# Save on CPU, Load on GPU
torch.save(model.state_dict(), PATH)

device = torch.device("cuda")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location="cuda:0"))
model.to(device)                    
```

